trigger:
- main

pool:
  name: 'Azure Pipelines' # Użyj nazwy puli agentów, którą utworzyłeś

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python --version
    docker-compose --version
  displayName: 'Check Python and Docker Compose versions'

- script: |
    docker-compose -f docker-compose.yml up -d
  displayName: 'Run Docker Compose'
