trigger:
- main

pool:
  name: 'Azure Pipelines'  

steps:
- checkout: self 

- script: |
    echo "Setting up Kubernetes context"
    az aks get-credentials --resource-group RG-1 --name tigcluster
    
    echo "Applying Kubernetes configurations"
    kubectl apply -f deploy/influxdb-deployment.yaml
    kubectl apply -f deploy/grafana-deployment.yaml
    kubectl apply -f deploy/telegraf-deployment.yaml
    kubectl apply -f deploy/persistent-volume-claim.yaml
  
displayName: 'Deploy to Kubernetes'
