trigger:
- main  # lub inna gałąź, z której chcesz uruchamiać pipeline

pool:
  name: 'Azure Piprlines'  # Upewnij się, że używasz odpowiedniej nazwy puli

steps:
- checkout: none  # Nie korzystaj z domyślnego repozytorium Azure DevOps

- script: |
    git clone https://github.com/akadiuszustasiak/tig-devops-azure
    cd tig-devops-azure/deploy
    docker-compose -f docker-compose.yml up -d
  displayName: 'Run Docker Compose'
